import uuid
from datetime import datetime, timezone

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


# ---------------------------------------------------------------------------
# Base
# ---------------------------------------------------------------------------

class Base(DeclarativeBase):
    """
    All ORM models inherit from this single Base.
    SQLAlchemy 2.0 style — no more declarative_base() factory.
    """
    pass


# ---------------------------------------------------------------------------
# Mixins  (use Python multiple inheritance — class Foo(UUIDMixin, TimestampMixin, Base))
# ---------------------------------------------------------------------------

class UUIDMixin:
    """
    Adds a UUID primary key generated by PostgreSQL itself (gen_random_uuid()).
    We never generate UUIDs in Python — the DB is the authority.
    """
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
        comment="Internal primary key — never exposed directly to end users",
    )


class TimestampMixin:
    """
    Adds created_at and updated_at to every model.

    - created_at  is set once by the DB on INSERT  (server_default)
    - updated_at  is set by the DB on every UPDATE (onupdate) and on INSERT
    """
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=False,
        comment="Row creation timestamp (UTC)",
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
        comment="Last update timestamp (UTC)",
    )