"""delete product_name from sales_products table

Revision ID: 22810484cd8e
Revises: 38cc5ad59daa
Create Date: 2026-07-03 21:58:56.093553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22810484cd8e'
down_revision: Union[str, Sequence[str], None] = '38cc5ad59daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_products', 'product_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_products', sa.Column('product_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False, comment='Product name — must be unique across all products'))
    # ### end Alembic commands ###
