"""added product_id a FK in sales_product table

Revision ID: 38cc5ad59daa
Revises: 561d8b7881c9
Create Date: 2026-07-01 10:19:00.621902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38cc5ad59daa'
down_revision: Union[str, Sequence[str], None] = '561d8b7881c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_products', sa.Column('product_id', sa.UUID(), nullable=False, comment='FK → products.id'))
    op.create_foreign_key(None, 'sales_products', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_products', type_='foreignkey')
    op.drop_column('sales_products', 'product_id')
    # ### end Alembic commands ###
