"""added password field in user table

Revision ID: 537ba2a3e6fd
Revises: dfeb6d601511
Create Date: 2026-06-15 20:12:41.790772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537ba2a3e6fd'
down_revision: Union[str, Sequence[str], None] = 'dfeb6d601511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False, comment='bcrypt hash — never store plain-text passwords'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
