"""added sales and sales_product tables

Revision ID: 561d8b7881c9
Revises: 6899f7c3004b
Create Date: 2026-06-21 21:11:57.308537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561d8b7881c9'
down_revision: Union[str, Sequence[str], None] = '6899f7c3004b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('name', sa.String(length=100), nullable=False, comment='sales name — must be unique'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total Sales Amount'),
    sa.Column('customer_id', sa.UUID(), nullable=False, comment='FK → customers.id'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Internal primary key — never exposed directly to end users'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sales_products',
    sa.Column('product_name', sa.String(length=150), nullable=False, comment='Product name — must be unique across all products'),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False, comment='Product quantity'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Current selling price — stored in the sale_items at time of sale'),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='multiply unit_price , quantity — stored in the sale_items at time of sale'),
    sa.Column('sales_id', sa.UUID(), nullable=False, comment='FK → sales.id'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Internal primary key — never exposed directly to end users'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_products')
    op.drop_table('sales')
    # ### end Alembic commands ###
