"""initial migration

Revision ID: eed771f45909
Revises: 
Create Date: 2026-06-09 16:43:04.744176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed771f45909'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('no', sa.String(length=100), nullable=False, comment='Number of Home/office'),
    sa.Column('street', sa.String(length=100), nullable=False, comment='Street of Home/office'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='City of Customer'),
    sa.Column('country', sa.String(length=100), nullable=False, comment='Country of Home/office'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Internal primary key — never exposed directly to end users'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Category name — must be unique'),
    sa.Column('country', sa.String(length=100), nullable=False, comment='Category name — must be unique'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional longer description'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Internal primary key — never exposed directly to end users'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customers',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Full display name'),
    sa.Column('email', sa.String(length=150), nullable=False, comment='Login email — must be unique across all users'),
    sa.Column('contact_no', sa.String(length=150), nullable=False, comment='contect number of user'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Soft-disable a user without deleting their history'),
    sa.Column('address_id', sa.UUID(), nullable=False, comment='FK → address.id'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Internal primary key — never exposed directly to end users'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_address_id'), 'customers', ['address_id'], unique=False)
    op.create_index(op.f('ix_customers_contact_no'), 'customers', ['contact_no'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_table('products',
    sa.Column('name', sa.String(length=150), nullable=False, comment='Product name — must be unique across all products'),
    sa.Column('sku', sa.String(length=60), nullable=False, comment='Stock Keeping Unit — unique internal product code e.g. ELEC-SAM-TV65'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional product description shown in UI'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Current selling price — stored in the sale_items at time of sale'),
    sa.Column('quantity_in_stock', sa.Integer(), server_default='0', nullable=False, comment='Current quantity on hand — updated by StockMovement events'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Soft-delete — inactive products hidden from sales but history preserved'),
    sa.Column('category_id', sa.UUID(), nullable=False, comment='FK → category.id'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Internal primary key — never exposed directly to end users'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_contact_no'), table_name='customers')
    op.drop_index(op.f('ix_customers_address_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('categories')
    op.drop_table('address')
    # ### end Alembic commands ###
